/* File: interpolate_to_pressure_levelsmodule.c
 * This file is auto-generated with f2py (version:2.0.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Apr 30 22:28:36 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *interpolate_to_pressure_levels_error;
static PyObject *interpolate_to_pressure_levels_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(interpolate_to_pressure_levels_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = interpolate_to_pressure_levels_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = interpolate_to_pressure_levels_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC_US(linear_interp,LINEAR_INTERP)(float*,float*,float*,float*,int*);
extern void F_WRAPPEDFUNC_US(interpolate_to_pressure_levels,INTERPOLATE_TO_PRESSURE_LEVELS)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* linear_interp *******************************/
static char doc_f2py_rout_interpolate_to_pressure_levels_linear_interp[] = "\
linear_interp = linear_interp(target,x,y,[n])\n\nWrapper for ``linear_interp``.\
\n\nParameters\n----------\n"
"target : input float\n"
"x : input rank-1 array('f') with bounds (n)\n"
"y : input rank-1 array('f') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(x, 0)\n"
"\nReturns\n-------\n"
"linear_interp : float";
/* extern void F_WRAPPEDFUNC_US(linear_interp,LINEAR_INTERP)(float*,float*,float*,float*,int*); */
static PyObject *f2py_rout_interpolate_to_pressure_levels_linear_interp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float linear_interp = 0;
    float target = 0;
    PyObject *target_capi = Py_None;
    float *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    float *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    static char *capi_kwlist[] = {"target","x","y","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:interpolate_to_pressure_levels.linear_interp",\
        capi_kwlist,&target_capi,&x_capi,&y_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable linear_interp */
    /* Processing variable target */
        f2py_success = float_from_pyobj(&target,target_capi,"interpolate_to_pressure_levels.linear_interp() 1st argument (target) can't be converted to float");
    if (f2py_success) {
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.linear_interp: failed to create array from the 2nd argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (float *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable n */
    if (n_capi == Py_None) n = shape(x, 0); else
        f2py_success = int_from_pyobj(&n,n_capi,"interpolate_to_pressure_levels.linear_interp() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x, 0) == n,"shape(x, 0) == n","1st keyword n","linear_interp:n=%d",n) {
    /* Processing variable y */
    y_Dims[0]=n;
    capi_y_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.linear_interp: failed to create array from the 3rd argument `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,y_Dims,y_Rank,  capi_y_intent,y_capi,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (float *)(PyArray_DATA(capi_y_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&linear_interp,&target,x,y,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",linear_interp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_y_as_array!=y_capi) {
        Py_XDECREF(capi_y_as_array); }
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    } /*CHECKSCALAR(shape(x, 0) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    } /*if (f2py_success) of target*/
    /* End of cleaning variable target */
    /* End of cleaning variable linear_interp */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of linear_interp ****************************/

/*********************** interpolate_to_pressure_levels ***********************/
static char doc_f2py_rout_interpolate_to_pressure_levels_interpolate_to_pressure_levels[] = "\
interpolate_to_pressure_levels(era5_levels,modis_levels,T_era5,W_era5,Z_era5,surface_pressures,W_surface,T_skin,T_sst,T_modis,W_modis,Z_modis)\n\nWrapper for ``interpolate_to_pressure_levels``.\
\n\nParameters\n----------\n"
"era5_levels : input rank-1 array('f') with bounds (f2py_era5_levels_d0)\n"
"modis_levels : input rank-1 array('f') with bounds (f2py_modis_levels_d0)\n"
"T_era5 : input rank-3 array('f') with bounds (f2py_T_era5_d0,f2py_T_era5_d1,f2py_T_era5_d2)\n"
"W_era5 : input rank-3 array('f') with bounds (f2py_W_era5_d0,f2py_W_era5_d1,f2py_W_era5_d2)\n"
"Z_era5 : input rank-3 array('f') with bounds (f2py_Z_era5_d0,f2py_Z_era5_d1,f2py_Z_era5_d2)\n"
"surface_pressures : input rank-2 array('f') with bounds (f2py_surface_pressures_d0,f2py_surface_pressures_d1)\n"
"W_surface : input rank-2 array('f') with bounds (f2py_W_surface_d0,f2py_W_surface_d1)\n"
"T_skin : input rank-2 array('f') with bounds (f2py_T_skin_d0,f2py_T_skin_d1)\n"
"T_sst : input rank-2 array('f') with bounds (f2py_T_sst_d0,f2py_T_sst_d1)\n"
"T_modis : in/output rank-3 array('f') with bounds (f2py_T_modis_d0,f2py_T_modis_d1,f2py_T_modis_d2)\n"
"W_modis : in/output rank-3 array('f') with bounds (f2py_W_modis_d0,f2py_W_modis_d1,f2py_W_modis_d2)\n"
"Z_modis : in/output rank-3 array('f') with bounds (f2py_Z_modis_d0,f2py_Z_modis_d1,f2py_Z_modis_d2)";
/* extern void F_WRAPPEDFUNC_US(interpolate_to_pressure_levels,INTERPOLATE_TO_PRESSURE_LEVELS)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_interpolate_to_pressure_levels_interpolate_to_pressure_levels(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float *era5_levels = NULL;
    npy_intp era5_levels_Dims[1] = {-1};
    const int era5_levels_Rank = 1;
    PyArrayObject *capi_era5_levels_as_array = NULL;
    int capi_era5_levels_intent = 0;
    PyObject *era5_levels_capi = Py_None;
    float *modis_levels = NULL;
    npy_intp modis_levels_Dims[1] = {-1};
    const int modis_levels_Rank = 1;
    PyArrayObject *capi_modis_levels_as_array = NULL;
    int capi_modis_levels_intent = 0;
    PyObject *modis_levels_capi = Py_None;
    float *T_era5 = NULL;
    npy_intp T_era5_Dims[3] = {-1, -1, -1};
    const int T_era5_Rank = 3;
    PyArrayObject *capi_T_era5_as_array = NULL;
    int capi_T_era5_intent = 0;
    PyObject *T_era5_capi = Py_None;
    float *W_era5 = NULL;
    npy_intp W_era5_Dims[3] = {-1, -1, -1};
    const int W_era5_Rank = 3;
    PyArrayObject *capi_W_era5_as_array = NULL;
    int capi_W_era5_intent = 0;
    PyObject *W_era5_capi = Py_None;
    float *Z_era5 = NULL;
    npy_intp Z_era5_Dims[3] = {-1, -1, -1};
    const int Z_era5_Rank = 3;
    PyArrayObject *capi_Z_era5_as_array = NULL;
    int capi_Z_era5_intent = 0;
    PyObject *Z_era5_capi = Py_None;
    float *surface_pressures = NULL;
    npy_intp surface_pressures_Dims[2] = {-1, -1};
    const int surface_pressures_Rank = 2;
    PyArrayObject *capi_surface_pressures_as_array = NULL;
    int capi_surface_pressures_intent = 0;
    PyObject *surface_pressures_capi = Py_None;
    float *W_surface = NULL;
    npy_intp W_surface_Dims[2] = {-1, -1};
    const int W_surface_Rank = 2;
    PyArrayObject *capi_W_surface_as_array = NULL;
    int capi_W_surface_intent = 0;
    PyObject *W_surface_capi = Py_None;
    float *T_skin = NULL;
    npy_intp T_skin_Dims[2] = {-1, -1};
    const int T_skin_Rank = 2;
    PyArrayObject *capi_T_skin_as_array = NULL;
    int capi_T_skin_intent = 0;
    PyObject *T_skin_capi = Py_None;
    float *T_sst = NULL;
    npy_intp T_sst_Dims[2] = {-1, -1};
    const int T_sst_Rank = 2;
    PyArrayObject *capi_T_sst_as_array = NULL;
    int capi_T_sst_intent = 0;
    PyObject *T_sst_capi = Py_None;
    float *T_modis = NULL;
    npy_intp T_modis_Dims[3] = {-1, -1, -1};
    const int T_modis_Rank = 3;
    PyArrayObject *capi_T_modis_as_array = NULL;
    int capi_T_modis_intent = 0;
    PyObject *T_modis_capi = Py_None;
    float *W_modis = NULL;
    npy_intp W_modis_Dims[3] = {-1, -1, -1};
    const int W_modis_Rank = 3;
    PyArrayObject *capi_W_modis_as_array = NULL;
    int capi_W_modis_intent = 0;
    PyObject *W_modis_capi = Py_None;
    float *Z_modis = NULL;
    npy_intp Z_modis_Dims[3] = {-1, -1, -1};
    const int Z_modis_Rank = 3;
    PyArrayObject *capi_Z_modis_as_array = NULL;
    int capi_Z_modis_intent = 0;
    PyObject *Z_modis_capi = Py_None;
    int f2py_era5_levels_d0 = 0;
    int f2py_modis_levels_d0 = 0;
    int f2py_T_era5_d0 = 0;
    int f2py_T_era5_d1 = 0;
    int f2py_T_era5_d2 = 0;
    int f2py_W_era5_d0 = 0;
    int f2py_W_era5_d1 = 0;
    int f2py_W_era5_d2 = 0;
    int f2py_Z_era5_d0 = 0;
    int f2py_Z_era5_d1 = 0;
    int f2py_Z_era5_d2 = 0;
    int f2py_surface_pressures_d0 = 0;
    int f2py_surface_pressures_d1 = 0;
    int f2py_W_surface_d0 = 0;
    int f2py_W_surface_d1 = 0;
    int f2py_T_skin_d0 = 0;
    int f2py_T_skin_d1 = 0;
    int f2py_T_sst_d0 = 0;
    int f2py_T_sst_d1 = 0;
    int f2py_T_modis_d0 = 0;
    int f2py_T_modis_d1 = 0;
    int f2py_T_modis_d2 = 0;
    int f2py_W_modis_d0 = 0;
    int f2py_W_modis_d1 = 0;
    int f2py_W_modis_d2 = 0;
    int f2py_Z_modis_d0 = 0;
    int f2py_Z_modis_d1 = 0;
    int f2py_Z_modis_d2 = 0;
    static char *capi_kwlist[] = {"era5_levels","modis_levels","T_era5","W_era5","Z_era5","surface_pressures","W_surface","T_skin","T_sst","T_modis","W_modis","Z_modis",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOO|:interpolate_to_pressure_levels.interpolate_to_pressure_levels",\
        capi_kwlist,&era5_levels_capi,&modis_levels_capi,&T_era5_capi,&W_era5_capi,&Z_era5_capi,&surface_pressures_capi,&W_surface_capi,&T_skin_capi,&T_sst_capi,&T_modis_capi,&W_modis_capi,&Z_modis_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable era5_levels */
    ;
    capi_era5_levels_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 1st argument `era5_levels`";
    capi_era5_levels_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,era5_levels_Dims,era5_levels_Rank,  capi_era5_levels_intent,era5_levels_capi,capi_errmess);
    if (capi_era5_levels_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        era5_levels = (float *)(PyArray_DATA(capi_era5_levels_as_array));

    /* Processing variable modis_levels */
    ;
    capi_modis_levels_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 2nd argument `modis_levels`";
    capi_modis_levels_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,modis_levels_Dims,modis_levels_Rank,  capi_modis_levels_intent,modis_levels_capi,capi_errmess);
    if (capi_modis_levels_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        modis_levels = (float *)(PyArray_DATA(capi_modis_levels_as_array));

    /* Processing variable T_era5 */
    ;
    capi_T_era5_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 3rd argument `T_era5`";
    capi_T_era5_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,T_era5_Dims,T_era5_Rank,  capi_T_era5_intent,T_era5_capi,capi_errmess);
    if (capi_T_era5_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        T_era5 = (float *)(PyArray_DATA(capi_T_era5_as_array));

    /* Processing variable W_era5 */
    ;
    capi_W_era5_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 4th argument `W_era5`";
    capi_W_era5_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,W_era5_Dims,W_era5_Rank,  capi_W_era5_intent,W_era5_capi,capi_errmess);
    if (capi_W_era5_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        W_era5 = (float *)(PyArray_DATA(capi_W_era5_as_array));

    /* Processing variable Z_era5 */
    ;
    capi_Z_era5_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 5th argument `Z_era5`";
    capi_Z_era5_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,Z_era5_Dims,Z_era5_Rank,  capi_Z_era5_intent,Z_era5_capi,capi_errmess);
    if (capi_Z_era5_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Z_era5 = (float *)(PyArray_DATA(capi_Z_era5_as_array));

    /* Processing variable surface_pressures */
    ;
    capi_surface_pressures_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 6th argument `surface_pressures`";
    capi_surface_pressures_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,surface_pressures_Dims,surface_pressures_Rank,  capi_surface_pressures_intent,surface_pressures_capi,capi_errmess);
    if (capi_surface_pressures_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        surface_pressures = (float *)(PyArray_DATA(capi_surface_pressures_as_array));

    /* Processing variable W_surface */
    ;
    capi_W_surface_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 7th argument `W_surface`";
    capi_W_surface_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,W_surface_Dims,W_surface_Rank,  capi_W_surface_intent,W_surface_capi,capi_errmess);
    if (capi_W_surface_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        W_surface = (float *)(PyArray_DATA(capi_W_surface_as_array));

    /* Processing variable T_skin */
    ;
    capi_T_skin_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 8th argument `T_skin`";
    capi_T_skin_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,T_skin_Dims,T_skin_Rank,  capi_T_skin_intent,T_skin_capi,capi_errmess);
    if (capi_T_skin_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        T_skin = (float *)(PyArray_DATA(capi_T_skin_as_array));

    /* Processing variable T_sst */
    ;
    capi_T_sst_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 9th argument `T_sst`";
    capi_T_sst_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,T_sst_Dims,T_sst_Rank,  capi_T_sst_intent,T_sst_capi,capi_errmess);
    if (capi_T_sst_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        T_sst = (float *)(PyArray_DATA(capi_T_sst_as_array));

    /* Processing variable T_modis */
    ;
    capi_T_modis_intent |= F2PY_INTENT_INOUT;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 10th argument `T_modis`";
    capi_T_modis_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,T_modis_Dims,T_modis_Rank,  capi_T_modis_intent,T_modis_capi,capi_errmess);
    if (capi_T_modis_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        T_modis = (float *)(PyArray_DATA(capi_T_modis_as_array));

    /* Processing variable W_modis */
    ;
    capi_W_modis_intent |= F2PY_INTENT_INOUT;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 11st argument `W_modis`";
    capi_W_modis_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,W_modis_Dims,W_modis_Rank,  capi_W_modis_intent,W_modis_capi,capi_errmess);
    if (capi_W_modis_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        W_modis = (float *)(PyArray_DATA(capi_W_modis_as_array));

    /* Processing variable Z_modis */
    ;
    capi_Z_modis_intent |= F2PY_INTENT_INOUT;
    const char * capi_errmess = "interpolate_to_pressure_levels.interpolate_to_pressure_levels.interpolate_to_pressure_levels: failed to create array from the 12nd argument `Z_modis`";
    capi_Z_modis_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,Z_modis_Dims,Z_modis_Rank,  capi_Z_modis_intent,Z_modis_capi,capi_errmess);
    if (capi_Z_modis_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = interpolate_to_pressure_levels_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Z_modis = (float *)(PyArray_DATA(capi_Z_modis_as_array));

    /* Processing variable f2py_era5_levels_d0 */
    f2py_era5_levels_d0 = shape(era5_levels, 0);
    /* Processing variable f2py_modis_levels_d0 */
    f2py_modis_levels_d0 = shape(modis_levels, 0);
    /* Processing variable f2py_T_era5_d0 */
    f2py_T_era5_d0 = shape(T_era5, 0);
    /* Processing variable f2py_T_era5_d1 */
    f2py_T_era5_d1 = shape(T_era5, 1);
    /* Processing variable f2py_T_era5_d2 */
    f2py_T_era5_d2 = shape(T_era5, 2);
    /* Processing variable f2py_W_era5_d0 */
    f2py_W_era5_d0 = shape(W_era5, 0);
    /* Processing variable f2py_W_era5_d1 */
    f2py_W_era5_d1 = shape(W_era5, 1);
    /* Processing variable f2py_W_era5_d2 */
    f2py_W_era5_d2 = shape(W_era5, 2);
    /* Processing variable f2py_Z_era5_d0 */
    f2py_Z_era5_d0 = shape(Z_era5, 0);
    /* Processing variable f2py_Z_era5_d1 */
    f2py_Z_era5_d1 = shape(Z_era5, 1);
    /* Processing variable f2py_Z_era5_d2 */
    f2py_Z_era5_d2 = shape(Z_era5, 2);
    /* Processing variable f2py_surface_pressures_d0 */
    f2py_surface_pressures_d0 = shape(surface_pressures, 0);
    /* Processing variable f2py_surface_pressures_d1 */
    f2py_surface_pressures_d1 = shape(surface_pressures, 1);
    /* Processing variable f2py_W_surface_d0 */
    f2py_W_surface_d0 = shape(W_surface, 0);
    /* Processing variable f2py_W_surface_d1 */
    f2py_W_surface_d1 = shape(W_surface, 1);
    /* Processing variable f2py_T_skin_d0 */
    f2py_T_skin_d0 = shape(T_skin, 0);
    /* Processing variable f2py_T_skin_d1 */
    f2py_T_skin_d1 = shape(T_skin, 1);
    /* Processing variable f2py_T_sst_d0 */
    f2py_T_sst_d0 = shape(T_sst, 0);
    /* Processing variable f2py_T_sst_d1 */
    f2py_T_sst_d1 = shape(T_sst, 1);
    /* Processing variable f2py_T_modis_d0 */
    f2py_T_modis_d0 = shape(T_modis, 0);
    /* Processing variable f2py_T_modis_d1 */
    f2py_T_modis_d1 = shape(T_modis, 1);
    /* Processing variable f2py_T_modis_d2 */
    f2py_T_modis_d2 = shape(T_modis, 2);
    /* Processing variable f2py_W_modis_d0 */
    f2py_W_modis_d0 = shape(W_modis, 0);
    /* Processing variable f2py_W_modis_d1 */
    f2py_W_modis_d1 = shape(W_modis, 1);
    /* Processing variable f2py_W_modis_d2 */
    f2py_W_modis_d2 = shape(W_modis, 2);
    /* Processing variable f2py_Z_modis_d0 */
    f2py_Z_modis_d0 = shape(Z_modis, 0);
    /* Processing variable f2py_Z_modis_d1 */
    f2py_Z_modis_d1 = shape(Z_modis, 1);
    /* Processing variable f2py_Z_modis_d2 */
    f2py_Z_modis_d2 = shape(Z_modis, 2);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(era5_levels,modis_levels,T_era5,W_era5,Z_era5,surface_pressures,W_surface,T_skin,T_sst,T_modis,W_modis,Z_modis,&f2py_era5_levels_d0,&f2py_modis_levels_d0,&f2py_T_era5_d0,&f2py_T_era5_d1,&f2py_T_era5_d2,&f2py_W_era5_d0,&f2py_W_era5_d1,&f2py_W_era5_d2,&f2py_Z_era5_d0,&f2py_Z_era5_d1,&f2py_Z_era5_d2,&f2py_surface_pressures_d0,&f2py_surface_pressures_d1,&f2py_W_surface_d0,&f2py_W_surface_d1,&f2py_T_skin_d0,&f2py_T_skin_d1,&f2py_T_sst_d0,&f2py_T_sst_d1,&f2py_T_modis_d0,&f2py_T_modis_d1,&f2py_T_modis_d2,&f2py_W_modis_d0,&f2py_W_modis_d1,&f2py_W_modis_d2,&f2py_Z_modis_d0,&f2py_Z_modis_d1,&f2py_Z_modis_d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_Z_modis_d2 */
    /* End of cleaning variable f2py_Z_modis_d1 */
    /* End of cleaning variable f2py_Z_modis_d0 */
    /* End of cleaning variable f2py_W_modis_d2 */
    /* End of cleaning variable f2py_W_modis_d1 */
    /* End of cleaning variable f2py_W_modis_d0 */
    /* End of cleaning variable f2py_T_modis_d2 */
    /* End of cleaning variable f2py_T_modis_d1 */
    /* End of cleaning variable f2py_T_modis_d0 */
    /* End of cleaning variable f2py_T_sst_d1 */
    /* End of cleaning variable f2py_T_sst_d0 */
    /* End of cleaning variable f2py_T_skin_d1 */
    /* End of cleaning variable f2py_T_skin_d0 */
    /* End of cleaning variable f2py_W_surface_d1 */
    /* End of cleaning variable f2py_W_surface_d0 */
    /* End of cleaning variable f2py_surface_pressures_d1 */
    /* End of cleaning variable f2py_surface_pressures_d0 */
    /* End of cleaning variable f2py_Z_era5_d2 */
    /* End of cleaning variable f2py_Z_era5_d1 */
    /* End of cleaning variable f2py_Z_era5_d0 */
    /* End of cleaning variable f2py_W_era5_d2 */
    /* End of cleaning variable f2py_W_era5_d1 */
    /* End of cleaning variable f2py_W_era5_d0 */
    /* End of cleaning variable f2py_T_era5_d2 */
    /* End of cleaning variable f2py_T_era5_d1 */
    /* End of cleaning variable f2py_T_era5_d0 */
    /* End of cleaning variable f2py_modis_levels_d0 */
    /* End of cleaning variable f2py_era5_levels_d0 */
    if((PyObject *)capi_Z_modis_as_array!=Z_modis_capi) {
        Py_XDECREF(capi_Z_modis_as_array); }
    }  /* if (capi_Z_modis_as_array == NULL) ... else of Z_modis */
    /* End of cleaning variable Z_modis */
    if((PyObject *)capi_W_modis_as_array!=W_modis_capi) {
        Py_XDECREF(capi_W_modis_as_array); }
    }  /* if (capi_W_modis_as_array == NULL) ... else of W_modis */
    /* End of cleaning variable W_modis */
    if((PyObject *)capi_T_modis_as_array!=T_modis_capi) {
        Py_XDECREF(capi_T_modis_as_array); }
    }  /* if (capi_T_modis_as_array == NULL) ... else of T_modis */
    /* End of cleaning variable T_modis */
    if((PyObject *)capi_T_sst_as_array!=T_sst_capi) {
        Py_XDECREF(capi_T_sst_as_array); }
    }  /* if (capi_T_sst_as_array == NULL) ... else of T_sst */
    /* End of cleaning variable T_sst */
    if((PyObject *)capi_T_skin_as_array!=T_skin_capi) {
        Py_XDECREF(capi_T_skin_as_array); }
    }  /* if (capi_T_skin_as_array == NULL) ... else of T_skin */
    /* End of cleaning variable T_skin */
    if((PyObject *)capi_W_surface_as_array!=W_surface_capi) {
        Py_XDECREF(capi_W_surface_as_array); }
    }  /* if (capi_W_surface_as_array == NULL) ... else of W_surface */
    /* End of cleaning variable W_surface */
    if((PyObject *)capi_surface_pressures_as_array!=surface_pressures_capi) {
        Py_XDECREF(capi_surface_pressures_as_array); }
    }  /* if (capi_surface_pressures_as_array == NULL) ... else of surface_pressures */
    /* End of cleaning variable surface_pressures */
    if((PyObject *)capi_Z_era5_as_array!=Z_era5_capi) {
        Py_XDECREF(capi_Z_era5_as_array); }
    }  /* if (capi_Z_era5_as_array == NULL) ... else of Z_era5 */
    /* End of cleaning variable Z_era5 */
    if((PyObject *)capi_W_era5_as_array!=W_era5_capi) {
        Py_XDECREF(capi_W_era5_as_array); }
    }  /* if (capi_W_era5_as_array == NULL) ... else of W_era5 */
    /* End of cleaning variable W_era5 */
    if((PyObject *)capi_T_era5_as_array!=T_era5_capi) {
        Py_XDECREF(capi_T_era5_as_array); }
    }  /* if (capi_T_era5_as_array == NULL) ... else of T_era5 */
    /* End of cleaning variable T_era5 */
    if((PyObject *)capi_modis_levels_as_array!=modis_levels_capi) {
        Py_XDECREF(capi_modis_levels_as_array); }
    }  /* if (capi_modis_levels_as_array == NULL) ... else of modis_levels */
    /* End of cleaning variable modis_levels */
    if((PyObject *)capi_era5_levels_as_array!=era5_levels_capi) {
        Py_XDECREF(capi_era5_levels_as_array); }
    }  /* if (capi_era5_levels_as_array == NULL) ... else of era5_levels */
    /* End of cleaning variable era5_levels */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of interpolate_to_pressure_levels *******************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"linear_interp",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(linear_interp,LINEAR_INTERP),  (f2py_init_func)f2py_rout_interpolate_to_pressure_levels_linear_interp,doc_f2py_rout_interpolate_to_pressure_levels_linear_interp},
    {"interpolate_to_pressure_levels",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(interpolate_to_pressure_levels,INTERPOLATE_TO_PRESSURE_LEVELS),  (f2py_init_func)f2py_rout_interpolate_to_pressure_levels_interpolate_to_pressure_levels,doc_f2py_rout_interpolate_to_pressure_levels_interpolate_to_pressure_levels},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "interpolate_to_pressure_levels",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_interpolate_to_pressure_levels(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = interpolate_to_pressure_levels_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module interpolate_to_pressure_levels (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'interpolate_to_pressure_levels' is auto-generated with f2py (version:2.0.2).\nFunctions:\n"
"    linear_interp = linear_interp(target,x,y,n=shape(x, 0))\n"
"    interpolate_to_pressure_levels(era5_levels,modis_levels,T_era5,W_era5,Z_era5,surface_pressures,W_surface,T_skin,T_sst,T_modis,W_modis,Z_modis)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    interpolate_to_pressure_levels_error = PyErr_NewException ("interpolate_to_pressure_levels.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_interpolate_to_pressure_levels_error", interpolate_to_pressure_levels_error);
    Py_DECREF(interpolate_to_pressure_levels_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

    {
      extern float F_FUNC_US(linear_interp,LINEAR_INTERP)(void);
      PyObject* o = PyDict_GetItemString(d,"linear_interp");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(linear_interp,LINEAR_INTERP),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("linear_interp");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern void F_FUNC_US(interpolate_to_pressure_levels,INTERPOLATE_TO_PRESSURE_LEVELS)(void);
      PyObject* o = PyDict_GetItemString(d,"interpolate_to_pressure_levels");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(interpolate_to_pressure_levels,INTERPOLATE_TO_PRESSURE_LEVELS),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("interpolate_to_pressure_levels");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"interpolate_to_pressure_levels");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
