!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.0.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapinterpolate_to_pressure_levels (era5_levels, mo&
     &dis_levels, T_era5, W_era5, Z_era5, surface_pressures, W_surface, &
     &T_skin, T_sst, T_modis, W_modis, Z_modis, f2py_era5_levels_d0, f2p&
     &y_modis_levels_d0, f2py_T_era5_d0, f2py_T_era5_d1, f2py_T_era5_d2,&
     & f2py_W_era5_d0, f2py_W_era5_d1, f2py_W_era5_d2, f2py_Z_era5_d0, f&
     &2py_Z_era5_d1, f2py_Z_era5_d2, f2py_surface_pressures_d0, f2py_sur&
     &face_pressures_d1, f2py_W_surface_d0, f2py_W_surface_d1, f2py_T_sk&
     &in_d0, f2py_T_skin_d1, f2py_T_sst_d0, f2py_T_sst_d1, f2py_T_modis_&
     &d0, f2py_T_modis_d1, f2py_T_modis_d2, f2py_W_modis_d0, f2py_W_modi&
     &s_d1, f2py_W_modis_d2, f2py_Z_modis_d0, f2py_Z_modis_d1, f2py_Z_mo&
     &dis_d2)
      integer f2py_era5_levels_d0
      integer f2py_modis_levels_d0
      integer f2py_T_era5_d0
      integer f2py_T_era5_d1
      integer f2py_T_era5_d2
      integer f2py_W_era5_d0
      integer f2py_W_era5_d1
      integer f2py_W_era5_d2
      integer f2py_Z_era5_d0
      integer f2py_Z_era5_d1
      integer f2py_Z_era5_d2
      integer f2py_surface_pressures_d0
      integer f2py_surface_pressures_d1
      integer f2py_W_surface_d0
      integer f2py_W_surface_d1
      integer f2py_T_skin_d0
      integer f2py_T_skin_d1
      integer f2py_T_sst_d0
      integer f2py_T_sst_d1
      integer f2py_T_modis_d0
      integer f2py_T_modis_d1
      integer f2py_T_modis_d2
      integer f2py_W_modis_d0
      integer f2py_W_modis_d1
      integer f2py_W_modis_d2
      integer f2py_Z_modis_d0
      integer f2py_Z_modis_d1
      integer f2py_Z_modis_d2
      real(kind=4) era5_levels(f2py_era5_levels_d0)
      real(kind=4) modis_levels(f2py_modis_levels_d0)
      real(kind=4) T_era5(f2py_T_era5_d0,f2py_T_era5_d1,f2py_T_era5_d2)
      real(kind=4) W_era5(f2py_W_era5_d0,f2py_W_era5_d1,f2py_W_era5_d2)
      real(kind=4) Z_era5(f2py_Z_era5_d0,f2py_Z_era5_d1,f2py_Z_era5_d2)
      real(kind=4) surface_pressures(f2py_surface_pressures_d0,f2py_surf&
     &ace_pressures_d1)
      real(kind=4) W_surface(f2py_W_surface_d0,f2py_W_surface_d1)
      real(kind=4) T_skin(f2py_T_skin_d0,f2py_T_skin_d1)
      real(kind=4) T_sst(f2py_T_sst_d0,f2py_T_sst_d1)
      real(kind=4) T_modis(f2py_T_modis_d0,f2py_T_modis_d1,f2py_T_modis_&
     &d2)
      real(kind=4) W_modis(f2py_W_modis_d0,f2py_W_modis_d1,f2py_W_modis_&
     &d2)
      real(kind=4) Z_modis(f2py_Z_modis_d0,f2py_Z_modis_d1,f2py_Z_modis_&
     &d2)
      interface
      
            subroutine interpolate_to_pressure_levels(era5_levels,modis_&
     &levels,T_era5,W_era5,Z_era5,surface_pressures,W_surface,T_skin,T_s&
     &st,T_modis,W_modis,Z_modis) 
                real(kind=4), intent(in),dimension(:) :: era5_levels
                real(kind=4), intent(in),dimension(:) :: modis_levels
                real(kind=4), intent(in),dimension(:,:,:) :: T_era5
                real(kind=4), intent(in),dimension(:,:,:) :: W_era5
                real(kind=4), intent(in),dimension(:,:,:) :: Z_era5
                real(kind=4), intent(in),dimension(:,:) :: surface_press&
     &ures
                real(kind=4), intent(in),dimension(:,:) :: W_surface
                real(kind=4), intent(in),dimension(:,:) :: T_skin
                real(kind=4), intent(in),dimension(:,:) :: T_sst
                real(kind=4), intent(inout),dimension(:,:,:) :: T_modis
                real(kind=4), intent(inout),dimension(:,:,:) :: W_modis
                real(kind=4), intent(inout),dimension(:,:,:) :: Z_modis
                interface  
                    function linear_interp(target,x,y,n) 
                        real(kind=4), intent(in) :: target
                        real(kind=4), intent(in),dimension(n) :: x
                        real(kind=4), intent(in),dimension(n) :: y
                        integer, intent(in) :: n
                    end function linear_interp
                end interface 
            end subroutine interpolate_to_pressure_levels
      end interface
      call interpolate_to_pressure_levels(era5_levels, modis_levels, T_e&
     &ra5, W_era5, Z_era5, surface_pressures, W_surface, T_skin, T_sst, &
     &T_modis, W_modis, Z_modis)
      end

