C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.2.6)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraplinear_interp (linear_interpf2pywrap, tar
     &get, x, y, n)
      external linear_interp
      real(kind=4) target
      integer n
      real(kind=4) x(n)
      real(kind=4) y(n)
      real(kind=4) linear_interpf2pywrap
      real(kind=4)  linear_interp
      linear_interpf2pywrap = linear_interp(target, x, y, n)
      end

