/* File: misr_cth_to_pressuremodule.c
 * This file is auto-generated with f2py (version:2.0.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Apr 25 17:18:40 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *misr_cth_to_pressure_error;
static PyObject *misr_cth_to_pressure_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(misr_cth_to_pressure_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = misr_cth_to_pressure_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(height_to_log_pressure,HEIGHT_TO_LOG_PRESSURE)(float*,float*,int*,int*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*************************** height_to_log_pressure ***************************/
static char doc_f2py_rout_misr_cth_to_pressure_height_to_log_pressure[] = "\
pressure_at_cth = height_to_log_pressure(geo_height,misr_cth,[rows,cols])\n\nWrapper for ``height_to_log_pressure``.\
\n\nParameters\n----------\n"
"geo_height : input rank-3 array('f') with bounds (101,rows,cols)\n"
"misr_cth : input rank-2 array('f') with bounds (rows,cols)\n"
"\nOther Parameters\n----------------\n"
"rows : input int, optional\n    Default: shape(geo_height, 1)\n"
"cols : input int, optional\n    Default: shape(geo_height, 2)\n"
"\nReturns\n-------\n"
"pressure_at_cth : rank-2 array('f') with bounds (rows,cols)";
/* extern void F_FUNC_US(height_to_log_pressure,HEIGHT_TO_LOG_PRESSURE)(float*,float*,int*,int*,float*); */
static PyObject *f2py_rout_misr_cth_to_pressure_height_to_log_pressure(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float *geo_height = NULL;
    npy_intp geo_height_Dims[3] = {-1, -1, -1};
    const int geo_height_Rank = 3;
    PyArrayObject *capi_geo_height_as_array = NULL;
    int capi_geo_height_intent = 0;
    PyObject *geo_height_capi = Py_None;
    float *misr_cth = NULL;
    npy_intp misr_cth_Dims[2] = {-1, -1};
    const int misr_cth_Rank = 2;
    PyArrayObject *capi_misr_cth_as_array = NULL;
    int capi_misr_cth_intent = 0;
    PyObject *misr_cth_capi = Py_None;
    int rows = 0;
    PyObject *rows_capi = Py_None;
    int cols = 0;
    PyObject *cols_capi = Py_None;
    float *pressure_at_cth = NULL;
    npy_intp pressure_at_cth_Dims[2] = {-1, -1};
    const int pressure_at_cth_Rank = 2;
    PyArrayObject *capi_pressure_at_cth_as_array = NULL;
    int capi_pressure_at_cth_intent = 0;
    static char *capi_kwlist[] = {"geo_height","misr_cth","rows","cols",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|OO:misr_cth_to_pressure.height_to_log_pressure",\
        capi_kwlist,&geo_height_capi,&misr_cth_capi,&rows_capi,&cols_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable geo_height */
    geo_height_Dims[0]=101;
    capi_geo_height_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "misr_cth_to_pressure.misr_cth_to_pressure.height_to_log_pressure: failed to create array from the 1st argument `geo_height`";
    capi_geo_height_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,geo_height_Dims,geo_height_Rank,  capi_geo_height_intent,geo_height_capi,capi_errmess);
    if (capi_geo_height_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = misr_cth_to_pressure_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        geo_height = (float *)(PyArray_DATA(capi_geo_height_as_array));

    /* Processing variable rows */
    if (rows_capi == Py_None) rows = shape(geo_height, 1); else
        f2py_success = int_from_pyobj(&rows,rows_capi,"misr_cth_to_pressure.height_to_log_pressure() 1st keyword (rows) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(geo_height, 1) == rows,"shape(geo_height, 1) == rows","1st keyword rows","height_to_log_pressure:rows=%d",rows) {
    /* Processing variable cols */
    if (cols_capi == Py_None) cols = shape(geo_height, 2); else
        f2py_success = int_from_pyobj(&cols,cols_capi,"misr_cth_to_pressure.height_to_log_pressure() 2nd keyword (cols) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(geo_height, 2) == cols,"shape(geo_height, 2) == cols","2nd keyword cols","height_to_log_pressure:cols=%d",cols) {
    /* Processing variable misr_cth */
    misr_cth_Dims[0]=rows,misr_cth_Dims[1]=cols;
    capi_misr_cth_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "misr_cth_to_pressure.misr_cth_to_pressure.height_to_log_pressure: failed to create array from the 2nd argument `misr_cth`";
    capi_misr_cth_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,misr_cth_Dims,misr_cth_Rank,  capi_misr_cth_intent,misr_cth_capi,capi_errmess);
    if (capi_misr_cth_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = misr_cth_to_pressure_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        misr_cth = (float *)(PyArray_DATA(capi_misr_cth_as_array));

    /* Processing variable pressure_at_cth */
    pressure_at_cth_Dims[0]=rows,pressure_at_cth_Dims[1]=cols;
    capi_pressure_at_cth_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "misr_cth_to_pressure.misr_cth_to_pressure.height_to_log_pressure: failed to create array from the hidden `pressure_at_cth`";
    capi_pressure_at_cth_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,pressure_at_cth_Dims,pressure_at_cth_Rank,  capi_pressure_at_cth_intent,Py_None,capi_errmess);
    if (capi_pressure_at_cth_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = misr_cth_to_pressure_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pressure_at_cth = (float *)(PyArray_DATA(capi_pressure_at_cth_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(geo_height,misr_cth,&rows,&cols,pressure_at_cth);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_pressure_at_cth_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_pressure_at_cth_as_array == NULL) ... else of pressure_at_cth */
    /* End of cleaning variable pressure_at_cth */
    if((PyObject *)capi_misr_cth_as_array!=misr_cth_capi) {
        Py_XDECREF(capi_misr_cth_as_array); }
    }  /* if (capi_misr_cth_as_array == NULL) ... else of misr_cth */
    /* End of cleaning variable misr_cth */
    } /*CHECKSCALAR(shape(geo_height, 2) == cols)*/
    } /*if (f2py_success) of cols*/
    /* End of cleaning variable cols */
    } /*CHECKSCALAR(shape(geo_height, 1) == rows)*/
    } /*if (f2py_success) of rows*/
    /* End of cleaning variable rows */
    if((PyObject *)capi_geo_height_as_array!=geo_height_capi) {
        Py_XDECREF(capi_geo_height_as_array); }
    }  /* if (capi_geo_height_as_array == NULL) ... else of geo_height */
    /* End of cleaning variable geo_height */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of height_to_log_pressure ***********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"height_to_log_pressure",-1,{{-1}},0,0,(char *)  F_FUNC_US(height_to_log_pressure,HEIGHT_TO_LOG_PRESSURE),  (f2py_init_func)f2py_rout_misr_cth_to_pressure_height_to_log_pressure,doc_f2py_rout_misr_cth_to_pressure_height_to_log_pressure},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "misr_cth_to_pressure",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_misr_cth_to_pressure(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = misr_cth_to_pressure_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module misr_cth_to_pressure (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'misr_cth_to_pressure' is auto-generated with f2py (version:2.0.2).\nFunctions:\n"
"    pressure_at_cth = height_to_log_pressure(geo_height,misr_cth,rows=shape(geo_height, 1),cols=shape(geo_height, 2))\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    misr_cth_to_pressure_error = PyErr_NewException ("misr_cth_to_pressure.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_misr_cth_to_pressure_error", misr_cth_to_pressure_error);
    Py_DECREF(misr_cth_to_pressure_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"misr_cth_to_pressure");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
