       SUBROUTINE MODIS_SMF_SETDYNAMICMSG(CODE,STRING_USER,FUNC_NAME)
       IMPLICIT NONE

C      -----------------------------------------------------------------------
C      !F77
C
C       !DESCRIPTION: 
C
C       WRITES A MESSAGE STRING TO THE LOGSTATUS FILE.  THE
C       COMPLETE MESSAGE CONSISTS OF THREE PIECES:  A PREDEFINED MODIS
C       OR SDPTK STATUS MESSAGE; A DYNAMIC MESSAGE SEGMENT (STRING_USER)
C       PASSED BY THE CALLING PROGRAM; AND THE NAME OF THE FUNCTION OR 
C       SUBROUTINE THAT CALLS MODIS_SMF_SETDYNAMICMSG. 
C
C       !INPUT PARAMETERS:  
C
C        INTEGER    CODE - A NAMED CONSTANT RELATED TO A PREDEFINED MODIS 
C                     OR SDP TK MESSAGE STRING
C        CHARACTER  STRING_USER - A DYNAMIC MESSAGE STRING DEFINED BY 
C                            CALLING PROGRAM
C        CHARACTER  FUNC_NAME - NAME OF MODULE REPORTING MESSAGE
C
C        !OUTPUT PARAMETERS:     NONE
C
C      !REVISION HISTORY:
C
C      !TEAM-UNIQUE HEADER: 
C
C      THIS SOFTWARE WAS DEVELOPED BY THE MODIS SCIENCE DATA SUPPORT
C      TEAM FOR THE NATIONAL AERONAUTICS AND SPACE ADMINISTRATION,
C      GODDARD SPACE FLIGHT CENTER, UNDER CONTRACT NAS5-32373.
C
C      !REFERENCES AND CREDITS:
C
C      WRITTEN BY VICKY LIN 
C
C      RESEARCH AND DATA SYSTEMS CORPORATION
C      SAIC/GSC MODIS SCIENCE DATA SUPPORT OFFICE
C      7501 FORBES BLVD, SEABROOK MD 20706
C
C      vlin@ltpmail.gsfc.nasa.gov
C
C      !DESIGN NOTES:
C
C      PREDEFINED MESSAGES WITH A FATAL STATUS LEVEL (i.e _F_) 
C      CAUSE PROGRAM TO EXIT VIA A FORTRAN EXIT STATEMENT.  
C
C      NONSUCCESSFUL COMPLETION OF EMBEDDED SUBROUTINE CALL ALSO 
C      CAUSE PROGRAM TO ABORT VIA A FORTRAN EXIT STATEMENT.  
C
C      EXTERNALS: 
C
C      NAMED CONSTANTS:
C            MODIS_F_GENERIC                (PGS_MODIS_39500.f)
C            PGS_S_SUCCESS                  (PGS_SMF.f)
C            PGS_TRUE                       (PGS_SMF.f)
C
C      FUNCTIONS AND SUBROUTINES:
C            STRING_LOC
C            CONCATENATE
C            PGS_SMF_SETDYNAMICMSG          (libPGSTK.a)
C            PGS_SMF_GETMSGBYCODE           (libPGSTK.a)
C            PGS_SMF_TESTFATALLEVEL         (libPGSTK.a)
C
C      !END
C      -----------------------------------------------------------------------

C SDP TOOLKIT HEADER FILE

C      INCLUDE 'PGS_SMF.f'
C      INCLUDE 'PGS_MODIS_39500.f'

C PARAMETER DECLARATIONS
	  integer PGS_SMF_MAX_MSGBUF_SIZE
	  parameter ( PGS_SMF_MAX_MSGBUF_SIZE = 480)
	  
      CHARACTER*(*)  FUNCNAME
      PARAMETER     (FUNCNAME = 'MODIS_SMF_SETDYNAMICMSG') 

      INTEGER        USER_MAX_BUF_LEN
      PARAMETER     (USER_MAX_BUF_LEN = 4096)
      

C DECLARATION OF VARIABLES
      CHARACTER*(*)  STRING_USER
      CHARACTER*(*)  FUNC_NAME
      CHARACTER*25   MSG25
      CHARACTER*512  MSG
C      CHARACTER*(USER_MAX_BUF_LEN) BUF

      INTEGER RTN,RETURNSTATUS, RETURNSTATUS2
      INTEGER FBYTE,LBYTE,CODE

C  FUNCTION DECLARATIONS
C      INTEGER STRING_LOC
C      INTEGER PGS_SMF_SETDYNAMICMSG
C      INTEGER PGS_SMF_GETMSGBYCODE
C      INTEGER PGS_SMF_TESTFATALLEVEL

C  INITIALIZE VARIABLES
C      BUF = ' '
      MSG = ' '
      RETURNSTATUS = 0
      RETURNSTATUS2 = 0

C  GET PREDEFINED MESSAGE FROM SEED FILE BASED ON ASSOCIATED NAMED
C  CONSTANT.  IF UNABLE TO GET PREDEFINED MESSAGE, REPORT PROBLEM
C  TO LOGSTATUS FILE AND EXIT. 


C  CONCATENATE USER MESSAGE WITH NMEMONIC MESSAGE.

C      CALL CONCATENATE(MSG,STRING_USER,BUF)


C  WRITE MESSAGE TO LOGSTATUS FILE.

      print*, CODE,trim(MSG), " ", trim(STRING_USER), " ", trim(FUNC_NAME)


C  TEST FOR FATAL ERROR.


      RETURN
      END

